Repository MoreliaTalk/morelia_server, pull requests merged in 2022-05, with the labels that each got.

#199 Dev doc #197
  .github/pull_request_template.md
  admin/control.py
  admin/general.py
  admin/login.py
  admin/logs.py
  docs/source/development.rst
  docs/source/doc.rst
  docs/source/install.rst
  mod/config/config.py
  mod/config/validator.py
  mod/db/dbhandler.py
  mod/error.py
  mod/lib.py
  mod/log_handler.py
  mod/protocol/mtp/worker.py
Labels: documentation

#202 Удалена админка и fastapi из проекта(#189), а также выполнены тикеты #172, #182, #195
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  README.md
  README_ENG.md
  admin/control.py
  admin/general.py
  admin/login.py
  admin/logs.py
  admin/templates/base_admin.html
  admin/templates/index_admin.html
  admin/templates/login.html
  admin/templates/logs_admin.html
  admin/templates/manage_admin.html
  admin/templates/status_admin.html
  manage.py
  mod/log_handler.py
  mod/protocol/mtp/worker.py
  server.py
  static/bootstrap.bundle.min.js
  static/bootstrap.min.css
  static/logo.png
  tests/test_admin.py
  tests/test_manage.py
  tests/test_server.py
Labels: bug, documentation, enhancement, dependencies, refactoring

#205 Изменён тег у нерелизных образов докер
  .github/workflows/docker-publish-image.yml
Labels: automatization
